on: [workflow_dispatch]

name: cargo-build

jobs:
  ci:
    runs-on:
      - nscloud-ubuntu-20.04-staging-amd64-4x16-with-cache
      - nscloud-cache-tag-test
      - nscloud-cache-size-50gb
    container:
      image: "nscr.io/01gr48y5j6qv4mgheyj4mchj76/rust:latest"
    steps:
      - run: pwd 
      - run: ls -lta $(pwd)/..
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          repository: chainflip-io/chainflip-backend
      - run: rustup default stable
      - run: cargo cf-build-release --locked
      - name: Breakpoint on failure
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: edganiukov,hugosantos,n-g,htr,nichtverstehen,gmichelo

  gh-runner:
    runs-on:
      - ubuntu-latest
    container:
      image: "bigmikes/custom-rust:latest"
    steps:
      - run: pwd 
      - run: ls -lta $(pwd)/..
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          repository: chainflip-io/chainflip-backend
      - run: rustup default stable
      - run: cargo cf-build-release --locked
      - name: Breakpoint on failure
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: edganiukov,hugosantos,n-g,htr,nichtverstehen,gmichelo
  
