on: [workflow_dispatch]

name: simple

jobs:
  ci:
    runs-on:
      - namespace-profile-testing-cache
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          # cat ~/.docker/config.json
          uname -a
          locale
          docker version
          docker buildx version
          cd /cache && df -h .
      
      - name: ls root 
        run: |
          ls -lta /

      - name: Checkout with Namespace Git mirrors cache
        uses: namespacelabs/nscloud-checkout-action@v1
        with:
          fetch-depth: 0

      - run: |
          pwd 

      - name: Setup Go cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            .ci_cache/cache

      - name: Breakpoint if tests failed
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 1h
          authorized-users: gmichelo,edganiukov,hugosantos

      - run: |
          ls $(pwd)

      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
          
      - run: go version

      - run: |
          time docker pull ubuntu
