on: [workflow_dispatch]

name: simple

jobs:
  ci:
    # runs-on:
    #   - nscloud-ubuntu-22.04-staging-amd64-4x16-with-cache
    #   - nscloud-cache-tag-cache-testdocker
    #   - nscloud-cache-size-100gb
    #   - nscloud-git-mirror-5gb
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x32
      - namespace-experiments:docker.buildx.proxy=server-side;use-next-nsc
    steps:
      - name: Env checks
        run: |
          # ulimit -a
          # aws --version
          docker buildx ls 
          docker version
          docker buildx version
          env
          sudo apt-get update -y 
          sudo apt-get install dnsutils -y
          dig rendezvous.namespace.so
          # cat ~/.docker/config.json
          # uname -a
          # locale
          
          # cd /cache && df -h .
          # node -v
      - name: Test checkout of another private repository
        uses: namespacelabs/nscloud-checkout-action@HEAD
        with:
          repository: gmichelo-dev/runner-tool-cache
          token: ${{ secrets.CHECKOUT_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: tools
          submodules: recursive
          persist-credentials: true

      - name: Test checkout of another private repository
        uses: namespacelabs/nscloud-checkout-action@HEAD
        with:
          repository: gmichelo-dev/test-private
          token: ${{ secrets.CHECKOUT_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: test-private
          submodules: recursive
          persist-credentials: true

      - name: Breakpoint if tests failed
        uses: namespacelabs/breakpoint-action@v0
        if: always()
        with:
          duration: 1h
          authorized-users: gmichelo  
    
      - run: pwd
      - run: getent passwd
      - run: getent group
      - run: gh version
      - run: ls -lta /home
      - run: ls -lta /usr
      - run: ls -lta /usr/share/dotnet
      - run: sudo cat /etc/sudoers
      - name: Test terraform
        run: |
          terraform version
  
      - name: Test aws cli and ssm plugin
        run: |
          aws --version
          session-manager-plugin

      - uses: actions/setup-dotnet@v4
        continue-on-error: true
        with:
          dotnet-version: 8.0.200
          cache: false
      - uses: actions/setup-dotnet@v3
        continue-on-error: true
        with:
          dotnet-version: 8.0.x
          cache: false

      - name: Test brew
        run: |
          brew --version
          ls -lta /home/linuxbrew
          brew update --preinstall

      

  # custom-ns-image:
  #   runs-on: namespace-profile-custom-image
  #   steps:
  #     - name: Check if psql is installed
  #       run: |
  #         psql --version  
  
  ci-gh-runner:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - run: pwd
      - run: which kubectl
      - run: which helm
      - run: getent passwd
      - run: getent group
      - name: Env checks
        run: |
          docker buildx ls 
          docker version
          docker buildx version
      - run: ls -lta /usr
      - run: ls -lta /home
      - run: ls -lta /usr/share
      - run: sudo cat /etc/sudoers
      - run: df -i
      - run: lsblk

      - name: Test checkout of another private repository
        uses: actions/checkout@v4
        with:
          repository: gmichelo-dev/runner-tool-cache
          token: ${{ secrets.CHECKOUT_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: tools
          submodules: recursive
          persist-credentials: true

      - name: Test checkout of another private repository
        uses: actions/checkout@v4
        with:
          repository: gmichelo-dev/test-private
          token: ${{ secrets.CHECKOUT_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: test-private
          submodules: recursive
          persist-credentials: true

      - name: Breakpoint if tests failed
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 1h
          authorized-users: gmichelo  

